### PR TITLE
Update 10.md

### PR DESCRIPTION
**Pull request by nsjuty**
added Phil

### CODE REVIEW

**Review by fbacall — APPROVED** [review]

**Comment by mihai-sysbio** [comment]
@nsjuty projects are meant to have only 2 co-leads this year. Adding a 3rd might be confusing, how about having "key participant"?

**Comment by PhilReedData** [comment]
What would be most useful for us is if I can push changes in our folder. I see you have just invited me there, @mihai-sysbio, thank you. We can change the file to list me as a key participant, though I thought I'd seen others with more than two leads listed in the flash slides. 

So am I right in thinking we will not have any file space in this repository this year, only the one Markdown file for each project? We can add all our relevant links to this file that point to wherever we need.

**Comment by mihai-sysbio** [comment]
Thanks for the follow-up @PhilReedData 

> We can change the file to list me as a key participant

That would be great for consistency

> though I thought I'd seen others with more than two leads listed in the flash slides.

Indeed, I've noticed that as well

> So am I right in thinking we will not have any file space in this repository this year, only the one Markdown file for each project? 

We encourage you to adopt the setup that would work best, whichever it is - active use of this repository (e.g., dedicated folder), or a separate repository

**Comment by PhilReedData** [comment]
I've made a new PR #16 to replace this one, since I can't edit the branch/patch that Nick used here.

**Comment by mihai-sysbio** [comment]
> I've made a new PR #16 to replace this one, since I can't edit the branch/patch that Nick used here.

Thanks @PhilReedData, with #16 merged I'll proceed to closing this one.

**Pull request closed without merging**
